qcacld-3.0 / qca-wifi-host-cmn: Fix enum conversions, strict-prototypes, and array-parameter warnings
Fixes clang compiler errors:
drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.c:6163:14: error: argument 'mdie' of type 'uint8_t[3]' (aka 'unsigned char[3]') with mismatched bound [-Werror,-Warray-parameter]
drivers/net/wireless/qualcomm/wcn39xx/qca-wifi-host-cmn/hif/src/ce/ce_main.c:1750:10: error: implicit conversion from enumeration type 'A_STATUS' to different enumeration type 'QDF_STATUS' [-Werror,-Wimplicit-enum-enum-cast]
drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/core/dp/htt/htt_h2t.c:610:10: error: implicit conversion from enumeration type 'A_STATUS' to different enumeration type 'QDF_STATUS' [-Werror,-Wimplicit-enum-enum-cast]
drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/core/dp/htt/htt_h2t.c:626:10: error: implicit conversion from enumeration type 'A_STATUS' to different enumeration type 'QDF_STATUS' [-Werror,-Wimplicit-enum-enum-cast]
drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/core/hdd/src/wlan_hdd_main.c:14209:25: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
drivers/net/wireless/qualcomm/wcn39xx/qca-wifi-host-cmn/hif/src/ce/ce_service.c:2773:34: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
drivers/net/wireless/qualcomm/wcn39xx/qca-wifi-host-cmn/target_if/core/src/target_if_main.c:81:40: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
drivers/net/wireless/qualcomm/wcn39xx/qca-wifi-host-cmn/wlan_cfg/wlan_cfg.c:292:49: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]

1. Align parser_api.h populate_mdie array parameter to mdie[SIR_MDIE_SIZE].
2. Return QDF_STATUS_E_FAILURE instead of A_ERROR in functions returning QDF_STATUS.
3. Add (void) to function definitions matching their existing header declarations.

Signed-off-by: thongass000 <tienthong2004@gmail.com>