arm64: sec_debug: Clean up unused variables in sec_debug_save_mmu_reg
Fixes clang unused-but-set-variable error:
arch/arm64/include/asm/sec_debug.h:108:19: error: variable 'which_el' set but not used [-Werror,-Wunused-but-set-variable]
        uint64_t pstate, which_el;
                         ^

In sec_debug_save_mmu_reg(), 'pstate' and 'which_el' were only used by a
commented-out pr_emerg call. Remove them, and simplify which_el in
sec_debug_save_core_reg().

Signed-off-by: thongass000 <tienthong2004@gmail.com>